"""add phone number

Revision ID: e2ea10fbc6f6
Revises: 906e845279e8
Create Date: 2022-08-15 19:44:13.718749

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e2ea10fbc6f6'
down_revision = '906e845279e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column(
        'phone_number', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'phone_number')
    # ### end Alembic commands ###









# def upgrade() -> None:
#     # ### commands auto generated by Alembic - please adjust! ###
#     op.create_table('user',
#     sa.Column('id', sa.Integer(), nullable=False),
#     sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
#     sa.Column('email', sa.String(), nullable=False),
#     sa.Column('password', sa.String(), nullable=True),
#     sa.Column('phone_number', sa.String(), nullable=True),
#     sa.PrimaryKeyConstraint('id'),
#     sa.UniqueConstraint('email')
#     )
#     op.drop_table('users')
#     op.drop_constraint('post_users_fkey', 'posts', type_='foreignkey')
#     op.create_foreign_key(None, 'posts', 'user', ['owner_id'], ['id'], ondelete='CASCADE')
#     op.drop_constraint('votes_user_id_fkey', 'votes', type_='foreignkey')
#     op.create_foreign_key(None, 'votes', 'user', ['user_id'], ['id'], ondelete='CASCADE')
#     # ### end Alembic commands ###


# def downgrade() -> None:
#     # ### commands auto generated by Alembic - please adjust! ###
#     op.drop_constraint(None, 'votes', type_='foreignkey')
#     op.create_foreign_key('votes_user_id_fkey', 'votes', 'users', ['user_id'], ['id'], ondelete='CASCADE')
#     op.drop_constraint(None, 'posts', type_='foreignkey')
#     op.create_foreign_key('post_users_fkey', 'posts', 'users', ['owner_id'], ['id'], ondelete='CASCADE')
#     op.create_table('users',
#     sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
#     sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
#     sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=False),
#     sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
#     sa.PrimaryKeyConstraint('id', name='users_pkey'),
#     sa.UniqueConstraint('email', name='users_email_key')
#     )
#     op.drop_table('user')
#     # ### end Alembic commands ###
